# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuitDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=25)),
                ('material', models.CharField(max_length=25)),
                ('lapel', models.CharField(max_length=25)),
                ('fit', models.CharField(max_length=25)),
                ('chest', models.IntegerField()),
                ('waist', models.IntegerField()),
                ('inseam', models.IntegerField()),
                ('seat', models.IntegerField()),
                ('sleeve', models.IntegerField()),
                ('shoulder', models.IntegerField()),
                ('bicep', models.IntegerField()),
                ('front_length', models.IntegerField()),
                ('outseam', models.IntegerField()),
                ('thigh', models.IntegerField()),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.Transaction')),
            ],
        ),
    ]
