# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_suitdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suitdetails',
            name='transaction',
        ),
    ]
