# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_remove_suitdetails_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('customer', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='Store.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='SuitDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=25)),
                ('material', models.CharField(max_length=25)),
                ('lapel', models.CharField(max_length=25)),
                ('fit', models.CharField(max_length=25)),
                ('chest', models.IntegerField()),
                ('waist', models.IntegerField()),
                ('inseam', models.IntegerField()),
                ('seat', models.IntegerField()),
                ('sleeve', models.IntegerField()),
                ('shoulder', models.IntegerField()),
                ('bicep', models.IntegerField()),
                ('front_length', models.IntegerField()),
                ('outseam', models.IntegerField()),
                ('thigh', models.IntegerField()),
                ('customer', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='Store.Customer')),
                ('lineItem', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='Store.LineItem')),
            ],
        ),
        migrations.DeleteModel(
            name='SuitDetails',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.Transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='Store.Customer'),
        ),
    ]
