# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 23:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_auto_20160609_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='name_first',
        ),
        migrations.AddField(
            model_name='customer',
            name='name_last',
            field=models.CharField(default= "", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='address',
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='city',
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='zip',
            field=models.IntegerField(default= -1,
            ))
    ]
